//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySearch.Console.Controls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportSearchResultControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportSearchResultControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySearch.Console.Controls.Resources.ExportSearchResultControl", typeof(ExportSearchResultControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Export.
        /// </summary>
        public static string EnableExport {
            get {
                return ResourceManager.GetString("EnableExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Export Folder.
        /// </summary>
        public static string HttpExportFolder {
            get {
                return ResourceManager.GetString("HttpExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP and Port.
        /// </summary>
        public static string IpAndPort {
            get {
                return ResourceManager.GetString("IpAndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy type.
        /// </summary>
        public static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Export Columns.
        /// </summary>
        public static string SelectExportColumns {
            get {
                return ResourceManager.GetString("SelectExportColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks Export Folder.
        /// </summary>
        public static string SocksExportFolder {
            get {
                return ResourceManager.GetString("SocksExportFolder", resourceCulture);
            }
        }
    }
}
