//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySearch.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySearch.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising closed.
        /// </summary>
        internal static string AdvertisingClosed {
            get {
                return ResourceManager.GetString("AdvertisingClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising opened in browser.
        /// </summary>
        internal static string AdvertisingOpenedInBrowser {
            get {
                return ResourceManager.GetString("AdvertisingOpenedInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All settings will be reverted to their defaults. Do you want to continue?.
        /// </summary>
        internal static string AllSettingsWillBeRevertedToTheirDefaults {
            get {
                return ResourceManager.GetString("AllSettingsWillBeRevertedToTheirDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;all sites&gt;.
        /// </summary>
        internal static string AllSites {
            get {
                return ResourceManager.GetString("AllSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... and on {0} more.
        /// </summary>
        internal static string AndMoreFormat {
            get {
                return ResourceManager.GetString("AndMoreFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in Geo IP, This option is good choice, but GeoIP data could be not latest and searching take some processor time.
        /// </summary>
        internal static string BuiltInGeoIPDescription {
            get {
                return ResourceManager.GetString("BuiltInGeoIPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in.
        /// </summary>
        internal static string BuiltInGeoIPName {
            get {
                return ResourceManager.GetString("BuiltInGeoIPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find installation url of Proxy Searcher.
        /// </summary>
        internal static string CannotFindInstallationUrl {
            get {
                return ResourceManager.GetString("CannotFindInstallationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set sock proxy for Firefox when socks version is not defined.
        /// </summary>
        internal static string CannotSetProxyForFirefoxWhenSocksVersionIsNotDefined {
            get {
                return ResourceManager.GetString("CannotSetProxyForFirefoxWhenSocksVersionIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update program. Do you want to do it manually?.
        /// </summary>
        internal static string CannotUpdateProgram {
            get {
                return ResourceManager.GetString("CannotUpdateProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        internal static string Chrome {
            get {
                return ResourceManager.GetString("Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom search.
        /// </summary>
        internal static string DefaultTabName {
            get {
                return ResourceManager.GetString("DefaultTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/donate.html.
        /// </summary>
        internal static string DonateLink {
            get {
                return ResourceManager.GetString("DonateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear blacklist?.
        /// </summary>
        internal static string DoYouReallyWantToClearBlacklist {
            get {
                return ResourceManager.GetString("DoYouReallyWantToClearBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear proxy usage history?.
        /// </summary>
        internal static string DoYouReallyWantToClearProxyUsageHistory {
            get {
                return ResourceManager.GetString("DoYouReallyWantToClearProxyUsageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this parse method?.
        /// </summary>
        internal static string DoYouReallyWantToDeleteThisParseMethod {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteThisParseMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser &apos;{0}&apos; should be restarted in order to set or clear proxy. Do you want to do it now?.
        /// </summary>
        internal static string DoYouWantToRestartBrowser {
            get {
                return ResourceManager.GetString("DoYouWantToRestartBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off.
        /// </summary>
        internal static string DummyGeoIP {
            get {
                return ResourceManager.GetString("DummyGeoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns off Geo IP. It is faster if compare with other options, but it will not give you proxy location.
        /// </summary>
        internal static string DummyGeoIPDescription {
            get {
                return ResourceManager.GetString("DummyGeoIPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has happened during test.
        /// </summary>
        internal static string ErrorHasHappenedDuringTest {
            get {
                return ResourceManager.GetString("ErrorHasHappenedDuringTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string EventLogSource {
            get {
                return ResourceManager.GetString("EventLogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/p/proxysearcher/discussion/yourfeedback/.
        /// </summary>
        internal static string FeedbackLink {
            get {
                return ResourceManager.GetString("FeedbackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox.
        /// </summary>
        internal static string Firefox {
            get {
                return ResourceManager.GetString("Firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /firstrun.
        /// </summary>
        internal static string FirstRunArgument {
            get {
                return ResourceManager.GetString("FirstRunArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in folder.
        /// </summary>
        internal static string FolderSearchEngine {
            get {
                return ResourceManager.GetString("FolderSearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have folder what contains files with proxies inside in the format [ip]:[port] you could select this search engine. Unfortunately it cannot discover new proxies, but it will check if proxies from files in selected folder are workable. This search engine will work fine together with export feature..
        /// </summary>
        internal static string FolderSearchEngineDescription {
            get {
                return ResourceManager.GetString("FolderSearchEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found and shown {0} proxies..
        /// </summary>
        internal static string FoundAndShownProxiesFormat {
            get {
                return ResourceManager.GetString("FoundAndShownProxiesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} and shown {1} proxies..
        /// </summary>
        internal static string FoundProxiesFormat {
            get {
                return ResourceManager.GetString("FoundProxiesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP (Google).
        /// </summary>
        internal static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google detects that your network sends automatic queries therefore this search type won&apos;t work at this moment. You could use search by list of urls which is not using google engine or try again later..
        /// </summary>
        internal static string GoogleDetectsSendingOfAutomaticQueries {
            get {
                return ResourceManager.GetString("GoogleDetectsSendingOfAutomaticQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://google.com.
        /// </summary>
        internal static string GoogleDotCom {
            get {
                return ResourceManager.GetString("GoogleDotCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;Google&lt;/title&gt;.
        /// </summary>
        internal static string GoogleDotComContent {
            get {
                return ResourceManager.GetString("GoogleDotComContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://google.com.
        /// </summary>
        internal static string GoogleDotComUrl {
            get {
                return ResourceManager.GetString("GoogleDotComUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses http://google.com site for proxy searching. If you cannot open http://google.com from browser then use other type of search engine.
        /// </summary>
        internal static string GoogleEngineDescription {
            get {
                return ResourceManager.GetString("GoogleEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid has no sorting.
        /// </summary>
        internal static string GridHasNoSorting {
            get {
                return ResourceManager.GetString("GridHasNoSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/projects/proxysearcher/.
        /// </summary>
        internal static string HomePageDeveloperLink {
            get {
                return ResourceManager.GetString("HomePageDeveloperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/.
        /// </summary>
        internal static string HomePageLink {
            get {
                return ResourceManager.GetString("HomePageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open findings as HTTP.
        /// </summary>
        internal static string HttpOpen {
            get {
                return ResourceManager.GetString("HttpOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP (list of urls).
        /// </summary>
        internal static string HttpPredefinedUrlList {
            get {
                return ResourceManager.GetString("HttpPredefinedUrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        internal static string HttpProxyType {
            get {
                return ResourceManager.GetString("HttpProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type allows to find http proxies.
        /// </summary>
        internal static string HttpProxyTypeDescription {
            get {
                return ResourceManager.GetString("HttpProxyTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet explorer.
        /// </summary>
        internal static string InternetExplorer {
            get {
                return ResourceManager.GetString("InternetExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming IP address: {0}
        ///Outgoing IP address: {1}.
        /// </summary>
        internal static string IPAddressDescriptionFormat {
            get {
                return ResourceManager.GetString("IPAddressDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Count {0}.
        /// </summary>
        internal static string JobCountFormat {
            get {
                return ResourceManager.GetString("JobCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual update proxy type.
        /// </summary>
        internal static string ManualUpdateProxyType {
            get {
                return ResourceManager.GetString("ManualUpdateProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of country was determined based on outgoing IP address &apos;{0}&apos;
        ///which is different from ingoing IP address &apos;{1}&apos;..
        /// </summary>
        internal static string NameOfCountryWasDeterminedBasedOnOutgoingAddress {
            get {
                return ResourceManager.GetString("NameOfCountryWasDeterminedBasedOnOutgoingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/p/proxysearcher/blog/.
        /// </summary>
        internal static string NewsLink {
            get {
                return ResourceManager.GetString("NewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy has been found.
        /// </summary>
        internal static string NoOneProxyHasBeenFound {
            get {
                return ResourceManager.GetString("NoOneProxyHasBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object of type &apos;{0}&apos; is not set yet.
        /// </summary>
        internal static string ObjectOfTypeIsNotSetYet {
            get {
                return ResourceManager.GetString("ObjectOfTypeIsNotSetYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like configuration of Proxy Searcher is not up-to-date. In order to fix that error open Tools-&gt;Settings and press &apos;Restore defaults&apos; button on General tab..
        /// </summary>
        internal static string OldConfigurationException {
            get {
                return ResourceManager.GetString("OldConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera.
        /// </summary>
        internal static string Opera {
            get {
                return ResourceManager.GetString("Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel.
        /// </summary>
        internal static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This search engine allows to combine a few other engines in one search criteria and run them simultaneously. Use it if you want to get benefits from a few different search engines in one search criteria..
        /// </summary>
        internal static string ParallelDescription {
            get {
                return ResourceManager.GetString("ParallelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing search application.
        /// </summary>
        internal static string PreparingApplication {
            get {
                return ResourceManager.GetString("PreparingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing geo ip service.
        /// </summary>
        internal static string PreparingGeoIpService {
            get {
                return ResourceManager.GetString("PreparingGeoIpService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing proxy checker.
        /// </summary>
        internal static string PreparingProxyChecker {
            get {
                return ResourceManager.GetString("PreparingProxyChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing proxy provider.
        /// </summary>
        internal static string PreparingProxyProvider {
            get {
                return ResourceManager.GetString("PreparingProxyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Url.
        /// </summary>
        internal static string ProxyCheckerByUrl {
            get {
                return ResourceManager.GetString("ProxyCheckerByUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Url And Keywords.
        /// </summary>
        internal static string ProxyCheckerByUrlAndKeywords {
            get {
                return ResourceManager.GetString("ProxyCheckerByUrlAndKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy checker could be useful if you don&apos;t have access to http page, but know his url and list of keywords what should be on page. This method is slower if compare with checker by IP:Port, but it filters better. If this checker don&apos;t return any results try to change keywords, probably page doesn&apos;t contains them. All specified keywords separates with space, all of them should be on the page, as keyword could be specified piece of http code without space(s). Because of content downloading this checker ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyCheckerByUrlAndKeywordsDescription {
            get {
                return ResourceManager.GetString("ProxyCheckerByUrlAndKeywordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy checker downloads content of specified url with and without proxy. If contents are similar then proxy is valid and will be returned by checker. This method is slower comparing with checker by IP:Port, but it filters better. If this checker doesn&apos;t return any results, try to change accuracy, probably page&apos;s content is too dynamic. Because of downloading page, content this checker takes internet traffic..
        /// </summary>
        internal static string ProxyCheckerByUrlDescription {
            get {
                return ResourceManager.GetString("ProxyCheckerByUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Searcher.
        /// </summary>
        internal static string ProxySearcherSource {
            get {
                return ResourceManager.GetString("ProxySearcherSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/static.html.
        /// </summary>
        internal static string ProxySearcherStaticHtml {
            get {
                return ResourceManager.GetString("ProxySearcherStaticHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A41B9664-9DF7-4EB5-8761-D56762497A44.
        /// </summary>
        internal static string ProxySearcherStaticHtmlContent {
            get {
                return ResourceManager.GetString("ProxySearcherStaticHtmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Searcher {0}.{1}.
        /// </summary>
        internal static string ProxySearcherVersionFormat {
            get {
                return ResourceManager.GetString("ProxySearcherVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration of selected search.
        /// </summary>
        internal static string ReadingConfigurationOfSelectedSearch {
            get {
                return ResourceManager.GetString("ReadingConfigurationOfSelectedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.##}.
        /// </summary>
        internal static string RoundFormat {
            get {
                return ResourceManager.GetString("RoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search cancelled.
        /// </summary>
        internal static string SearchCancelled {
            get {
                return ResourceManager.GetString("SearchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search finished.
        /// </summary>
        internal static string SearchFinished {
            get {
                return ResourceManager.GetString("SearchFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search initialization.
        /// </summary>
        internal static string SearchInitialization {
            get {
                return ResourceManager.GetString("SearchInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is cancelled on user request.
        /// </summary>
        internal static string SearchIsCancelledOnUserRequest {
            get {
                return ResourceManager.GetString("SearchIsCancelledOnUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is finished. {0} proxies was found.
        /// </summary>
        internal static string SearchIsFinishedProxiesWasFound {
            get {
                return ResourceManager.GetString("SearchIsFinishedProxiesWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is finished. No proxy was found. Change search query and try again.
        /// </summary>
        internal static string SearchIsFinishedProxiesWasNotFound {
            get {
                return ResourceManager.GetString("SearchIsFinishedProxiesWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search started.
        /// </summary>
        internal static string SearchStarted {
            get {
                return ResourceManager.GetString("SearchStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareStatistic.
        /// </summary>
        internal static string ShareCheckBox {
            get {
                return ResourceManager.GetString("ShareCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /shutdown.
        /// </summary>
        internal static string ShutdownArgument {
            get {
                return ResourceManager.GetString("ShutdownArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By IP:Port.
        /// </summary>
        internal static string SimpleProxyChecker {
            get {
                return ResourceManager.GetString("SimpleProxyChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This simple checker sees if ip address of candidate is alive and port is opened. Can be used for any proxy type searching. It is fast because it don&apos;t require any external services. It cannot check if candidate is workable proxy, therefore it would return unworkable proxies..
        /// </summary>
        internal static string SimpleProxyCheckerDescription {
            get {
                return ResourceManager.GetString("SimpleProxyCheckerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS (Google).
        /// </summary>
        internal static string SocksGoogleSearchType {
            get {
                return ResourceManager.GetString("SocksGoogleSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open findings as Socks.
        /// </summary>
        internal static string SocksOpen {
            get {
                return ResourceManager.GetString("SocksOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks (list of urls).
        /// </summary>
        internal static string SocksPredefinedUrlList {
            get {
                return ResourceManager.GetString("SocksPredefinedUrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS.
        /// </summary>
        internal static string SocksProxyType {
            get {
                return ResourceManager.GetString("SocksProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type allows to find socks proxies.
        /// </summary>
        internal static string SocksProxyTypeDesciption {
            get {
                return ResourceManager.GetString("SocksProxyTypeDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort type by &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string SortTypeIsNotSupported {
            get {
                return ResourceManager.GetString("SortTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string SpeedRespondTextFormat {
            get {
                return ResourceManager.GetString("SpeedRespondTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: {1} Mb/s
        ///Response time: {0} s.
        /// </summary>
        internal static string SpeedRespondTooltipFormat {
            get {
                return ResourceManager.GetString("SpeedRespondTooltipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test url doesn&apos;t match defined url.
        /// </summary>
        internal static string TestUrlDoesntMatchDefinedUrl {
            get {
                return ResourceManager.GetString("TestUrlDoesntMatchDefinedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This client doesn&apos;t support socks v5 proxies.
        /// </summary>
        internal static string ThisClientDoesntSupportSocks5Proxies {
            get {
                return ResourceManager.GetString("ThisClientDoesntSupportSocks5Proxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/p/proxysearcher/tickets/.
        /// </summary>
        internal static string TicketsLink {
            get {
                return ResourceManager.GetString("TicketsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check manually after search.
        /// </summary>
        internal static string TurnedOffProxyChecker {
            get {
                return ResourceManager.GetString("TurnedOffProxyChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy checker type retrieves all proxies without filtering. It could be useful of opening results from previous searches..
        /// </summary>
        internal static string TurnedOffProxyCheckerDetails {
            get {
                return ResourceManager.GetString("TurnedOffProxyCheckerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of proxy is not defined and this client doesn&apos;t support socks v5 proxies, so socks v5 will not work if you set proxy. Do you want to continue?.
        /// </summary>
        internal static string TypeOfProxyIsNotDefinedDoYouWantToContinue {
            get {
                return ResourceManager.GetString("TypeOfProxyIsNotDefinedDoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undetermined.
        /// </summary>
        internal static string Undetermined {
            get {
                return ResourceManager.GetString("Undetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of Proxy Searcher is available. Do you want to get it now?.
        /// </summary>
        internal static string UpdateIsReadyToInstall {
            get {
                return ResourceManager.GetString("UpdateIsReadyToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Url List.
        /// </summary>
        internal static string UrlListEngine {
            get {
                return ResourceManager.GetString("UrlListEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have list of urls what contains text with proxies in the format [ip]:[port] you could select this search engine. Unfortunately it cannot discover new sources of proxies, but it will be able to find new proxies if they appear on page..
        /// </summary>
        internal static string UrlListEngineDescription {
            get {
                return ResourceManager.GetString("UrlListEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait until current operation is finished.
        /// </summary>
        internal static string WaitUntilCurrentOperationIsFinished {
            get {
                return ResourceManager.GetString("WaitUntilCurrentOperationIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.webservicex.net/geoipservice.asmx.
        /// </summary>
        internal static string WebServiceNetGeoIPService {
            get {
                return ResourceManager.GetString("WebServiceNetGeoIPService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses http://www.webservicex.net/geoipservice.asmx service as Geo IP. If you cannot open http://www.webservicex.net/geoipservice.asmx from browser, use other type of Geo IP.
        /// </summary>
        internal static string WebServiceNetGeoIPServiceDescription {
            get {
                return ResourceManager.GetString("WebServiceNetGeoIPServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;Wikipedia&lt;/title&gt;.
        /// </summary>
        internal static string WikipediaContent {
            get {
                return ResourceManager.GetString("WikipediaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.wikipedia.org/.
        /// </summary>
        internal static string WikipediaDotOrgUrl {
            get {
                return ResourceManager.GetString("WikipediaDotOrgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon world128x128 {
            get {
                object obj = ResourceManager.GetObject("world128x128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete last search settings..
        /// </summary>
        internal static string YouCannotDeleteLastSearchSettings {
            get {
                return ResourceManager.GetString("YouCannotDeleteLastSearchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should clear value before set new one.
        /// </summary>
        internal static string YouShouldClearValueBeforeSetNewOne {
            get {
                return ResourceManager.GetString("YouShouldClearValueBeforeSetNewOne", resourceCulture);
            }
        }
    }
}
